apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-queue-storage
  namespace: dragonball-library
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    value: "storage5gvqxy7gckwwa"
  - name: queueName
    value: "queue"
  - name: route
    value: /background
  - name: accountKey
    value: "<SECRET_VALUE" 
  auth:
    secretStore: azure-keyvault
scopes:
- apiservice
- backgroundservice